/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Batch LOWESS smoothing. */
export declare class Lowess {
  /** Create a new batch LOWESS smoother. */
  constructor(options?: SmoothOptions | undefined | null)
  /** Fit the model. */
  fit(x: Float64Array, y: Float64Array, customWeights?: Float64Array | undefined | null): LowessResult
  /** Fit the model asynchronously. */
  fit_async(x: Float64Array, y: Float64Array, customWeights?: Float64Array | undefined | null): Promise<unknown>
}

/** Result of a LOWESS fit. */
export declare class LowessResult {
  /** Get the x values (same order as input). */
  get x(): Float64Array
  /** Get the smoothed y values. */
  get y(): Float64Array
  /** Get residuals (if requested). */
  get residuals(): Float64Array | null
  /** Get standard errors (if requested/computed). */
  get standard_errors(): Float64Array | null
  /** Get lower confidence bounds (if requested). */
  get confidence_lower(): Float64Array | null
  /** Get upper confidence bounds (if requested). */
  get confidence_upper(): Float64Array | null
  /** Get lower prediction bounds (if requested). */
  get prediction_lower(): Float64Array | null
  /** Get upper prediction bounds (if requested). */
  get prediction_upper(): Float64Array | null
  /** Get robustness weights (if requested). */
  get robustness_weights(): Float64Array | null
  /** Get the per-point local fit derivative (slope) (if requested). */
  get derivative(): Float64Array | null
  /** Get diagnostics (if requested). */
  get diagnostics(): Diagnostics | null
  /** Get cross-validation scores (if CV was performed). */
  get cv_scores(): Float64Array | null
  /** Get the fraction used for smoothing. */
  get fraction_used(): number
  /** Get the number of iterations performed. */
  get iterations_used(): number | null
  /**
   * Evaluate the fitted model at out-of-sample query points not in the training set.
   *
   * Requires `retain_model: true` to have been set on the builder before `fit()`.
   */
  predict(newX: Float64Array, options?: PredictOptions | undefined | null): PredictOutput
}

/** Online LOWESS smoother for real-time data. */
export declare class OnlineLowess {
  /** Create a new online LOWESS smoother. */
  constructor(options?: OnlineSmoothOptions | undefined | null, onlineOpts?: OnlineOptions | undefined | null)
  /** Add a single point and get the smoothed value if enough points are available. */
  add_point(x: number, y: number): OnlineOutput | null
}

/** Result of `LowessResult.predict()`. */
export declare class PredictOutput {
  /** Predicted y values, one per query point. */
  get y(): Float64Array
  /** Standard errors (if requested). */
  get standard_errors(): Float64Array | null
  /** Lower confidence interval bounds (if requested). */
  get confidence_lower(): Float64Array | null
  /** Upper confidence interval bounds (if requested). */
  get confidence_upper(): Float64Array | null
  /** Lower prediction interval bounds (if requested). */
  get prediction_lower(): Float64Array | null
  /** Upper prediction interval bounds (if requested). */
  get prediction_upper(): Float64Array | null
  /** Local fit's derivative (slope) at each query point (if requested). */
  get derivative(): Float64Array | null
}

/** Streaming LOWESS smoother for large datasets. */
export declare class StreamingLowess {
  /** Create a new streaming LOWESS smoother. */
  constructor(options?: StreamingSmoothOptions | undefined | null, streamingOpts?: StreamingOptions | undefined | null)
  /** Process a chunk of data. */
  process_chunk(x: Float64Array, y: Float64Array): LowessResult
  /** Finalize the stream and return remaining data. */
  finalize(): LowessResult
}

/** Diagnostic statistics for the LOWESS fit. */
export interface Diagnostics {
  /** Root Mean Squared Error. */
  rmse: number
  /** Mean Absolute Error. */
  mae: number
  /** R-squared (coefficient of determination). */
  r_squared: number
  /** Akaike Information Criterion (if computed). */
  aic?: number
  /** Corrected AIC (if computed). */
  aicc?: number
  /** Effective degrees of freedom (if computed). */
  effective_df?: number
  /** Residual standard deviation. */
  residual_sd: number
}

/** True if this addon was built with the `gpu` Cargo feature enabled. */
export declare function gpu_enabled(): boolean

/** Configuration options for online processing. */
export interface OnlineOptions {
  /** Maximum number of points to keep in the window. Default: 1000. */
  window_capacity?: number
  /** Minimum points required before smoothing starts. Default: 2. */
  min_points?: number
  /** Update mode ("full", "incremental"). Default: "incremental". */
  update_mode?: string
}

/** Result of a single online update step. */
export interface OnlineOutput {
  /** Smoothed value for the latest point. */
  y: number
  /** Standard error (if computed). */
  standard_error?: number
  /** Residual (raw input y minus this output's y) (if computed). */
  residual?: number
  /** Robustness weight for the latest point (if computed). */
  robustness_weight?: number
  /** Number of robustness iterations performed (if applicable). */
  iterations_used?: number
  /** Local fit derivative (slope) for the latest point (if requested). */
  derivative?: number
  /** Lower confidence interval bound for the latest point (if requested). */
  confidence_lower?: number
  /** Upper confidence interval bound for the latest point (if requested). */
  confidence_upper?: number
  /** Lower prediction interval bound for the latest point (if requested). */
  prediction_lower?: number
  /** Upper prediction interval bound for the latest point (if requested). */
  prediction_upper?: number
}

/**
 * Configuration options for online LOWESS smoothing.
 *
 * A subset of [`SmoothOptions`]: diagnostics, residuals, parallel execution,
 * cross-validation, `return_sorted`, and `backend` are all no-ops for online
 * processing (it handles one point at a time), so they aren't fields on
 * this type. `return_se`/`confidence_intervals`/`prediction_intervals`
 * require `update_mode = "full"`.
 */
export interface OnlineSmoothOptions {
  /** Smoothing fraction (0 < fraction <= 1). Default: 0.67. */
  fraction?: number
  /** Number of robustness iterations. Default: 3. */
  iterations?: number
  /**
   * Delta for interpolation speedup. Default: NaN (auto).
   * Set to 0.0 to disable interpolation.
   */
  delta?: number
  /** Weight function ("tricube", "epanechnikov", "gaussian", "uniform", "biweight", "triangle", "cosine"). Default: "tricube". */
  weight_function?: string
  /** Robustness method ("bisquare", "huber", "talwar"). Default: "bisquare". */
  robustness_method?: string
  /** Fallback strategy when weights are zero ("use_local_mean", "return_original", "return_none"). Default: "use_local_mean". */
  zero_weight_fallback?: string
  /** Boundary handling ("extend", "reflect", "zero", "noboundary"). Default: "extend". */
  boundary_policy?: string
  /** Scaling method ("mad", "mar", "mean"). Default: "mad". */
  scaling_method?: string
  /** Auto-convergence tolerance. Default: None. */
  auto_converge?: number
  /** Return robustness weights in result. Default: false. */
  return_robustness_weights?: boolean
  /** Return the per-point local fit derivative (slope) in result. Default: false. */
  return_derivative?: boolean
  /** Policy for non-finite (NaN/Inf) `x`/`y` values passed to `addPoint` ("error", "drop"). Default: "error". */
  missing?: string
  /** Compute standard errors. Requires `update_mode = "full"`. Default: false. */
  return_se?: boolean
  /** Calculate confidence intervals (e.g., 0.95). Requires `update_mode = "full"`. Default: None. */
  confidence_intervals?: number
  /** Calculate prediction intervals. Requires `update_mode = "full"`. Default: None. */
  prediction_intervals?: number
}

/** Options for `LowessResult.predict()`. */
export interface PredictOptions {
  /** Include standard errors in the output. Default: false. */
  return_se?: boolean
  /** Confidence interval coverage level (e.g. 0.95). Default: None. */
  confidence_level?: number
  /** Prediction interval coverage level (e.g. 0.95). Default: None. */
  prediction_level?: number
  /** Include the local fit's derivative (slope) in the output. Default: false. */
  return_derivative?: boolean
  /** Behavior for query points outside the training range ("clamp", "linear", "error"). Default: "clamp". */
  extrapolation?: string
  /**
   * Under "linear" extrapolation, the maximum allowed distance beyond the training
   * boundary before `predict()` errors instead of returning an unbounded value.
   */
  max_extrapolation_distance?: number
  /**
   * Maximum allowed distance to the farthest point in a query's local window
   * before `predict()` errors, catching in-range-but-sparse query points.
   */
  max_neighbor_distance?: number
}

/** Configuration options for LOWESS smoothing. */
export interface SmoothOptions {
  /** Smoothing fraction (0 < fraction <= 1). Default: 0.67. */
  fraction?: number
  /** Number of robustness iterations. Default: 3. */
  iterations?: number
  /**
   * Delta for interpolation speedup. Default: NaN (auto).
   * Set to 0.0 to disable interpolation.
   */
  delta?: number
  /** Weight function ("tricube", "epanechnikov", "gaussian", "uniform", "biweight", "triangle", "cosine"). Default: "tricube". */
  weight_function?: string
  /** Robustness method ("bisquare", "huber", "talwar"). Default: "bisquare". */
  robustness_method?: string
  /** Fallback strategy when weights are zero ("use_local_mean", "return_original", "return_none"). Default: "use_local_mean". */
  zero_weight_fallback?: string
  /** Boundary handling ("extend", "reflect", "zero", "noboundary"). Default: "extend". */
  boundary_policy?: string
  /** Scaling method ("mad", "mar", "mean"). Default: "mad". */
  scaling_method?: string
  /** Auto-convergence tolerance. Default: None. */
  auto_converge?: number
  /** Return residuals in result. Default: false. */
  return_residuals?: boolean
  /** Return robustness weights in result. Default: false. */
  return_robustness_weights?: boolean
  /** Return the per-point local fit derivative (slope) in result. Default: false. */
  return_derivative?: boolean
  /** Return diagnostics (RMSE, etc.). Default: false. */
  return_diagnostics?: boolean
  /** Calculate confidence intervals (e.g., 0.95). Default: None. */
  confidence_intervals?: number
  /** Calculate prediction intervals. Default: None. */
  prediction_intervals?: number
  /** Fractions to use for cross-validation. */
  cv_fractions?: Array<number>
  /** CV method ("loocv", "kfold"). Default: "kfold". */
  cv_method?: string
  /** Number of folds for K-Fold CV. Default: 5. */
  cv_k?: number
  /** Random seed for reproducible K-Fold cross-validation. Default: None. */
  cv_seed?: number
  /** Compute standard errors. Default: false. */
  return_se?: boolean
  /**
   * Return results sorted ascending by x instead of in original input order.
   * Default: false.
   */
  return_sorted?: boolean
  /** Enable parallel execution. Default: true. */
  parallel?: boolean
  /**
   * Execution backend: "cpu" (default) or "gpu" (requires the package to be
   * built with the `gpu` Cargo feature and a Vulkan/Metal/DX12-capable GPU).
   */
  backend?: string
  /** Policy for non-finite (NaN/Inf) values in input data ("error", "drop"). Default: "error". */
  missing?: string
  /** Retain the fitted model's training data, enabling `LowessResult.predict()`. Default: false. */
  retain_model?: boolean
}

/** Configuration options for streaming processing. */
export interface StreamingOptions {
  /** Size of each data chunk. Default: 5000. */
  chunk_size?: number
  /** Header/footer overlap size. Default: chunk_size / 10, min. 1. */
  overlap?: number
  /** Strategy for merging chunk overlaps. Default: "weighted_average". */
  merge_strategy?: string
}

/**
 * Configuration options for streaming LOWESS smoothing.
 *
 * A subset of [`SmoothOptions`]: cross-validation, `return_sorted`, and
 * `backend` are Batch-only and have no equivalent here, so they aren't
 * fields on this type.
 */
export interface StreamingSmoothOptions {
  /** Smoothing fraction (0 < fraction <= 1). Default: 0.67. */
  fraction?: number
  /** Number of robustness iterations. Default: 3. */
  iterations?: number
  /**
   * Delta for interpolation speedup. Default: NaN (auto).
   * Set to 0.0 to disable interpolation.
   */
  delta?: number
  /** Weight function ("tricube", "epanechnikov", "gaussian", "uniform", "biweight", "triangle", "cosine"). Default: "tricube". */
  weight_function?: string
  /** Robustness method ("bisquare", "huber", "talwar"). Default: "bisquare". */
  robustness_method?: string
  /** Fallback strategy when weights are zero ("use_local_mean", "return_original", "return_none"). Default: "use_local_mean". */
  zero_weight_fallback?: string
  /** Boundary handling ("extend", "reflect", "zero", "noboundary"). Default: "extend". */
  boundary_policy?: string
  /** Scaling method ("mad", "mar", "mean"). Default: "mad". */
  scaling_method?: string
  /** Auto-convergence tolerance. Default: None. */
  auto_converge?: number
  /** Return residuals in result. Default: false. */
  return_residuals?: boolean
  /** Return robustness weights in result. Default: false. */
  return_robustness_weights?: boolean
  /** Return the per-point local fit derivative (slope) in result. Default: false. */
  return_derivative?: boolean
  /** Return diagnostics (RMSE, etc.). Default: false. */
  return_diagnostics?: boolean
  /** Compute standard errors. Default: false. */
  return_se?: boolean
  /** Calculate confidence intervals (e.g., 0.95). Default: None. */
  confidence_intervals?: number
  /** Calculate prediction intervals. Default: None. */
  prediction_intervals?: number
  /** Enable parallel execution. Default: true. */
  parallel?: boolean
  /** Policy for non-finite (NaN/Inf) values in each chunk ("error", "drop"). Default: "error". */
  missing?: string
}
