/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

// Check for local build first (prioritize dev/CI environment)
if (existsSync(join(__dirname, 'fastlowess.node'))) {
  nativeBinding = require('./fastlowess.node')
} else {
  switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.android-arm64.node')
          } else {
            nativeBinding = require('fastlowess-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.android-arm-eabi.node')
          } else {
            nativeBinding = require('fastlowess-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.win32-x64-msvc.node')
          } else {
            nativeBinding = require('fastlowess-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-ia32-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('fastlowess-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-arm64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('fastlowess-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./fastlowess.darwin-universal.node')
      } else {
        switch (arch) {
          case 'x64':
            localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-x64.node'))
            try {
              if (localFileExisted) {
                nativeBinding = require('./fastlowess.darwin-x64.node')
              } else {
                nativeBinding = require('fastlowess-darwin-x64')
              }
            } catch (e) {
              loadError = e
            }
            break
          case 'arm64':
            localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-arm64.node'))
            try {
              if (localFileExisted) {
                nativeBinding = require('./fastlowess.darwin-arm64.node')
              } else {
                nativeBinding = require('fastlowess-darwin-arm64')
              }
            } catch (e) {
              loadError = e
            }
            break
          default:
            throw new Error(`Unsupported architecture on macOS: ${arch}`)
        }
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'fastlowess.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./fastlowess.freebsd-x64.node')
      } else {
        nativeBinding = require('fastlowess-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-x64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-x64-musl.node')
            } else {
              nativeBinding = require('fastlowess-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-x64-gnu.node')
            } else {
              nativeBinding = require('fastlowess-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-arm64-musl.node')
            } else {
              nativeBinding = require('fastlowess-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('fastlowess-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm-gnueabihf.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('fastlowess-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-riscv64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('fastlowess-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-riscv64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./fastlowess.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('fastlowess-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-s390x-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fastlowess.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('fastlowess-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
  }
}

if (!nativeBinding) {
    if (existsSync(join(__dirname, 'fastlowess.node'))) {
        nativeBinding = require('./fastlowess.node')
    } else {
        if (loadError) {
            throw loadError
        }
        throw new Error(`Failed to load native binding`)
    }
}

const { Lowess, StreamingLowess, OnlineLowess, LowessResultObj } = nativeBinding

module.exports.Lowess = Lowess
module.exports.StreamingLowess = StreamingLowess
module.exports.OnlineLowess = OnlineLowess
module.exports.LowessResultObj = LowessResultObj
