/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')
const gpuDownload = require('./gpu-download')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
    // For Node 10
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process').execSync('which ldd').toString().trim()
            return readFileSync(lddPath, 'utf8').includes('musl')
        } catch (e) {
            return true
        }
    } else {
        const { glibcVersionRuntime } = process.report.getReport().header
        return !glibcVersionRuntime
    }
}

// Check for local build first (prioritize dev/CI environment)
if (existsSync(join(__dirname, 'fastlowess.node'))) {
    nativeBinding = require('./fastlowess.node')
} else {
    switch (platform) {
        case 'android':
            switch (arch) {
                case 'arm64':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.android-arm64.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.android-arm64.node')
                        } else {
                            nativeBinding = require('fastlowess-android-arm64')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                case 'arm':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.android-arm-eabi.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.android-arm-eabi.node')
                        } else {
                            nativeBinding = require('fastlowess-android-arm-eabi')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                default:
                    throw new Error(`Unsupported architecture on Android ${arch}`)
            }
            break
        case 'win32':
            switch (arch) {
                case 'x64':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-x64-msvc.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.win32-x64-msvc.node')
                        } else {
                            nativeBinding = require('fastlowess-win32-x64-msvc')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                case 'ia32':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-ia32-msvc.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.win32-ia32-msvc.node')
                        } else {
                            nativeBinding = require('fastlowess-win32-ia32-msvc')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                case 'arm64':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.win32-arm64-msvc.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.win32-arm64-msvc.node')
                        } else {
                            nativeBinding = require('fastlowess-win32-arm64-msvc')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                default:
                    throw new Error(`Unsupported architecture on Windows: ${arch}`)
            }
            break
        case 'darwin':
            localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-universal.node'))
            try {
                if (localFileExisted) {
                    nativeBinding = require('./fastlowess.darwin-universal.node')
                } else {
                    switch (arch) {
                        case 'x64':
                            localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-x64.node'))
                            try {
                                if (localFileExisted) {
                                    nativeBinding = require('./fastlowess.darwin-x64.node')
                                } else {
                                    nativeBinding = require('fastlowess-darwin-x64')
                                }
                            } catch (e) {
                                loadError = e
                            }
                            break
                        case 'arm64':
                            localFileExisted = existsSync(join(__dirname, 'fastlowess.darwin-arm64.node'))
                            try {
                                if (localFileExisted) {
                                    nativeBinding = require('./fastlowess.darwin-arm64.node')
                                } else {
                                    nativeBinding = require('fastlowess-darwin-arm64')
                                }
                            } catch (e) {
                                loadError = e
                            }
                            break
                        default:
                            throw new Error(`Unsupported architecture on macOS: ${arch}`)
                    }
                }
            } catch (e) {
                loadError = e
            }
            break
        case 'freebsd':
            if (arch !== 'x64') {
                throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
            }
            localFileExisted = existsSync(join(__dirname, 'fastlowess.freebsd-x64.node'))
            try {
                if (localFileExisted) {
                    nativeBinding = require('./fastlowess.freebsd-x64.node')
                } else {
                    nativeBinding = require('fastlowess-freebsd-x64')
                }
            } catch (e) {
                loadError = e
            }
            break
        case 'linux':
            switch (arch) {
                case 'x64':
                    if (isMusl()) {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-x64-musl.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-x64-musl.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-x64-musl')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    } else {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-x64-gnu.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-x64-gnu.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-x64-gnu')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    }
                    break
                case 'arm64':
                    if (isMusl()) {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm64-musl.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-arm64-musl.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-arm64-musl')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    } else {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm64-gnu.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-arm64-gnu.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-arm64-gnu')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    }
                    break
                case 'arm':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-arm-gnueabihf.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.linux-arm-gnueabihf.node')
                        } else {
                            nativeBinding = require('fastlowess-linux-arm-gnueabihf')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                case 'riscv64':
                    if (isMusl()) {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-riscv64-musl.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-riscv64-musl.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-riscv64-musl')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    } else {
                        localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-riscv64-gnu.node'))
                        try {
                            if (localFileExisted) {
                                nativeBinding = require('./fastlowess.linux-riscv64-gnu.node')
                            } else {
                                nativeBinding = require('fastlowess-linux-riscv64-gnu')
                            }
                        } catch (e) {
                            loadError = e
                        }
                    }
                    break
                case 's390x':
                    localFileExisted = existsSync(join(__dirname, 'fastlowess.linux-s390x-gnu.node'))
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./fastlowess.linux-s390x-gnu.node')
                        } else {
                            nativeBinding = require('fastlowess-linux-s390x-gnu')
                        }
                    } catch (e) {
                        loadError = e
                    }
                    break
                default:
                    throw new Error(`Unsupported architecture on Linux: ${arch}`)
            }
            break
        default:
            throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
    }
}

if (!nativeBinding) {
    if (existsSync(join(__dirname, 'fastlowess.node'))) {
        nativeBinding = require('./fastlowess.node')
    } else {
        if (loadError) {
            throw loadError
        }
        throw new Error(`Failed to load native binding`)
    }
}

const {
    Lowess: _NativeLowess,
    StreamingLowess: _NativeStreamingLowess,
    OnlineLowess: _NativeOnlineLowess,
    LowessResult,
} = nativeBinding

// ---------------------------------------------------------------------------
// Option key validation
// ---------------------------------------------------------------------------

const _SMOOTH_OPTION_KEYS = new Set([
    'fraction', 'iterations', 'delta', 'weight_function', 'robustness_method',
    'zero_weight_fallback', 'boundary_policy', 'scaling_method', 'auto_converge',
    'return_residuals', 'return_robustness_weights', 'return_diagnostics',
    'confidence_intervals', 'prediction_intervals', 'cv_fractions', 'cv_method',
    'cv_k', 'cv_seed', 'return_se', 'parallel', 'backend',
])

const _STREAMING_OPTION_KEYS = new Set(['chunk_size', 'overlap', 'merge_strategy'])

const _ONLINE_OPTION_KEYS = new Set(['window_capacity', 'min_points', 'update_mode'])

function _validateOptions(opts, validKeys, typeName) {
    if (opts == null) return
    for (const key of Object.keys(opts)) {
        if (!validKeys.has(key)) {
            throw new TypeError(
                `Unknown ${typeName} key: "${key}". ` +
                `Valid keys: ${[...validKeys].sort().join(', ')}`
            )
        }
    }
}

// Normalize customWeights: ensure Float64Array for the native binding.
function _normalizeCustomWeights(cw) {
    if (cw == null) {
        return cw
    }
    if (cw instanceof Float64Array) {
        return cw
    }
    return Float64Array.from(cw)
}

// ---------------------------------------------------------------------------
// Wrapper classes: validate options, then delegate to native implementation
// ---------------------------------------------------------------------------

class Lowess extends _NativeLowess {
    constructor(opts) {
        _validateOptions(opts, _SMOOTH_OPTION_KEYS, 'SmoothOptions')
        if (opts && opts.backend === 'gpu' && !gpuAvailable()) {
            throw new Error(
                'GPU backend not installed in this build. Run `await fastlowess.installGpu()` ' +
                'once to download and install a GPU-enabled build, then restart Node.js. ' +
                'See https://thisisamirv.github.io/lowess-project/nodejs/ for details.'
            )
        }
        super(opts)
    }

    fit(x, y, customWeights) {
        return super.fit(x, y, _normalizeCustomWeights(customWeights))
    }

    fit_async(x, y, customWeights) {
        return super.fit_async(x, y, _normalizeCustomWeights(customWeights))
    }
}

class StreamingLowess extends _NativeStreamingLowess {
    constructor(opts, streamingOpts) {
        _validateOptions(opts, _SMOOTH_OPTION_KEYS, 'SmoothOptions')
        _validateOptions(streamingOpts, _STREAMING_OPTION_KEYS, 'StreamingOptions')
        super(opts, streamingOpts)
    }
}

class OnlineLowess extends _NativeOnlineLowess {
    constructor(opts, onlineOpts) {
        _validateOptions(opts, _SMOOTH_OPTION_KEYS, 'SmoothOptions')
        _validateOptions(onlineOpts, _ONLINE_OPTION_KEYS, 'OnlineOptions')
        super(opts, onlineOpts)
    }
}

module.exports.Lowess = Lowess
module.exports.StreamingLowess = StreamingLowess
module.exports.OnlineLowess = OnlineLowess
module.exports.LowessResult = LowessResult

// ---------------------------------------------------------------------------
// GPU backend: availability check + one-time downloader/installer
// ---------------------------------------------------------------------------

function gpuAvailable() {
    return typeof nativeBinding.gpu_enabled === 'function' && nativeBinding.gpu_enabled()
}

function _gpuPlatformSuffix() {
    if (platform === 'win32' && arch === 'x64') return 'win32-x64-msvc'
    if (platform === 'darwin' && arch === 'x64') return 'darwin-x64'
    if (platform === 'darwin' && arch === 'arm64') return 'darwin-arm64'
    if (platform === 'linux' && arch === 'x64' && !isMusl()) return 'linux-x64-gnu'
    return null
}

/**
 * Download and install the GPU-enabled fastlowess native binding for this
 * platform, then restart Node.js to use it.
 *
 * Fetches a prebuilt `.node` addon (built with the `gpu` Cargo feature) from
 * the matching GitHub Release and saves it as `fastlowess.node` next to this
 * file — the same local-override path this loader already checks first, so
 * no other configuration is needed. A running Node.js process cannot swap
 * an already-loaded native addon, so a restart is required afterwards.
 *
 * @param {{yes?: boolean}} [options] Pass `{ yes: true }` to skip the
 *   interactive y/N confirmation prompt (required when stdin is not a TTY).
 */
async function installGpu(options = {}) {
    const { yes = false } = options
    if (gpuAvailable()) {
        console.log('GPU backend is already active.')
        return
    }

    const suffix = _gpuPlatformSuffix()
    if (!suffix) {
        throw new Error(
            `No prebuilt GPU binary available for ${platform}-${arch}. ` +
            'Build from source instead: see https://thisisamirv.github.io/lowess-project/nodejs/'
        )
    }

    const { version } = require('./package.json')
    const assetName = `fastlowess-gpu.${suffix}.node`
    const url = `https://github.com/${gpuDownload.REPO}/releases/download/v${version}/${assetName}`
    const destPath = join(__dirname, 'fastlowess.node')

    if (!yes) {
        const ok = await gpuDownload.confirm(
            `Download and install ${assetName} from github.com/${gpuDownload.REPO}? [y/N] `
        )
        if (!ok) {
            console.log('Aborted.')
            return
        }
    }

    console.log(`Downloading ${url} ...`)
    try {
        await gpuDownload.downloadToFile(url, destPath)
    } catch (e) {
        throw new Error(
            `Failed to download ${url}: ${e.message}\n` +
            'A matching GPU build may not exist for this platform/version yet.'
        )
    }

    console.log(`GPU backend installed at ${destPath}.`)
    console.log('Restart Node.js for the change to take effect.')
}

module.exports.gpuAvailable = gpuAvailable
module.exports.installGpu = installGpu
