[package]
name = "fastlowess-go"
version = "3.2.1"
authors = ["Amir Valizadeh <thisisamirv@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/thisisamirv/lowess-project"
homepage = "https://github.com/thisisamirv/lowess-project"
documentation = "https://thisisamirv.github.io/lowess-project/go/"
rust-version = "1.89"
readme = "README.md"
description = "High-performance LOWESS (Locally Weighted Scatterplot Smoothing)"
keywords = ["lowess", "smoothing", "statistics", "regression", "bioinformatics"]
categories = ["science", "algorithms"]

[lib]
name = "fastlowess_go"
crate-type = ["staticlib"]

[dependencies]
fastLowess = { path = "../../crates/fastLowess", version = "3.2", features = [
    "cpu",
    "dev",
] }
libc = "0.2"

[build-dependencies]
cbindgen = "0.29"

[features]
default = []
gpu = ["fastLowess/gpu"]
