var searchData=
[
  ['a_20kernel_0',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md171',1,'']]],
  ['a_20known_20outlier_1',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md108',1,'']]],
  ['a_20policy_2',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md66',1,'']]],
  ['a_20scaling_20method_3',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md272',1,'']]],
  ['a_20strategy_4',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md183',1,'']]],
  ['absolute_20deviation_20default_5',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md266',1,'']]],
  ['absolute_20residual_6',['absolute residual',['../md_docs_2scaling.html#autotoc_md268',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md270',1,'Mean — Mean Absolute Residual']]],
  ['acceleration_7',['GPU Acceleration',['../md_docs_2api.html#autotoc_md30',1,'']]],
  ['adapter_20parameters_8',['Adapter Parameters',['../md_docs_2parameters.html#autotoc_md224',1,'']]],
  ['adapter_2dchoice_2emd_9',['adapter-choice.md',['../adapter-choice_8md.html',1,'']]],
  ['advantages_10',['Key Advantages',['../index.html#autotoc_md80',1,'']]],
  ['also_11',['also',['../md_docs_2use-case-real-time.html#autotoc_md305',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md118',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md287',1,'See Also'],['../md_docs_2gpu-backend.html#autotoc_md129',1,'See also'],['../md_docs_2use-case-time-series.html#autotoc_md323',1,'See Also']]],
  ['analysis_12',['analysis',['../md_docs_2use-case-time-series.html#autotoc_md317',1,'Multi-Scale Analysis'],['../md_docs_2use-case-time-series.html',1,'Time Series Analysis']]],
  ['api_13',['api',['../md_docs_2api.html',1,'API'],['../md_docs_2api-online.html',1,'OnlineLowess API'],['../md_docs_2api-streaming.html',1,'StreamingLowess API']]],
  ['api_2donline_2emd_14',['api-online.md',['../api-online_8md.html',1,'']]],
  ['api_2dstreaming_2emd_15',['api-streaming.md',['../api-streaming_8md.html',1,'']]],
  ['api_2emd_16',['api.md',['../api_8md.html',1,'']]],
  ['application_17',['Application',['../md_docs_2use-case-genomics.html#autotoc_md281',1,'']]],
  ['auto_20convergence_18',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md262',1,'']]],
  ['auto_5fconverge_19',['auto_converge',['../md_docs_2parameters.html#autotoc_md206',1,'']]],
  ['availability_20',['availability',['../md_docs_2intervals.html#autotoc_md151',1,'Availability'],['../md_docs_2cross-validation.html#autotoc_md98',1,'Availability'],['../md_docs_2gpu-backend.html#autotoc_md124',1,'Checking Availability']]],
  ['available_20kernels_21',['Available Kernels',['../md_docs_2kernels.html#autotoc_md155',1,'']]],
  ['average_22',['average',['../md_docs_2merge.html#autotoc_md175',1,'Average'],['../md_docs_2merge.html#autotoc_md181',1,'Weighted Average']]]
];
