var searchData=
[
  ['take_20first_0',['Take First',['../md_docs_2merge.html#autotoc_md198',1,'']]],
  ['take_20last_1',['Take Last',['../md_docs_2merge.html#autotoc_md200',1,'']]],
  ['talwar_2',['Talwar',['../md_docs_2robustness.html#autotoc_md275',1,'']]],
  ['the_20challenge_3',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md298',1,'']]],
  ['the_20fraction_20parameter_4',['The Fraction Parameter',['../md_docs_2concepts.html#autotoc_md91',1,'']]],
  ['the_20full_20documentation_20a_5',['📚 &lt;a href=&quot;https://thisisamirv.github.io/lowess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['this_20package_6',['Why this package?',['../index.html#autotoc_md8',1,'']]],
  ['thisisamirv_20github_20io_20lowess_20project_20cpp_20view_20the_20full_20documentation_20a_7',['📚 &lt;a href=&quot;https://thisisamirv.github.io/lowess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['time_20course_8',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md340',1,'']]],
  ['time_20dashboard_20example_9',['Real-Time Dashboard Example',['../md_docs_2use-case-real-time.html#autotoc_md318',1,'']]],
  ['time_20processing_10',['Real-Time Processing',['../md_docs_2use-case-real-time.html',1,'']]],
  ['time_20series_11',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'']]],
  ['time_20series_20analysis_12',['Time Series Analysis',['../md_docs_2use-case-time-series.html',1,'']]],
  ['to_20use_13',['to use',['../md_docs_2api-online.html#autotoc_md23',1,'When to Use'],['../md_docs_2api-streaming.html#autotoc_md33',1,'When to Use'],['../md_docs_2api.html#autotoc_md44',1,'When to Use']]],
  ['to_20use_20custom_20weights_14',['When to Use Custom Weights',['../md_docs_2custom-weights.html#autotoc_md125',1,'']]],
  ['trend_20extraction_15',['Basic Trend Extraction',['../md_docs_2use-case-time-series.html#autotoc_md330',1,'']]],
  ['triangle_16',['Triangle',['../md_docs_2kernels.html#autotoc_md188',1,'']]],
  ['tricube_20default_17',['Tricube (Default)',['../md_docs_2kernels.html#autotoc_md178',1,'']]],
  ['tt_20fastlowess_3a_3adiagnostics_20tt_18',['&lt;tt&gt;fastlowess::Diagnostics&lt;/tt&gt;',['../md_docs_2api.html#autotoc_md58',1,'']]],
  ['tt_20fastlowess_3a_3alowess_20tt_19',['&lt;tt&gt;fastlowess::Lowess&lt;/tt&gt;',['../md_docs_2api.html#autotoc_md46',1,'']]],
  ['tt_20fastlowess_3a_3alowessresult_20tt_20',['tt fastlowess::lowessresult tt',['../md_docs_2api-streaming.html#autotoc_md37',1,'&lt;tt&gt;fastlowess::LowessResult&lt;/tt&gt;'],['../md_docs_2api.html#autotoc_md57',1,'&lt;tt&gt;fastlowess::LowessResult&lt;/tt&gt;']]],
  ['tt_20fastlowess_3a_3aonlinelowess_20tt_21',['&lt;tt&gt;fastlowess::OnlineLowess&lt;/tt&gt;',['../md_docs_2api-online.html#autotoc_md25',1,'']]],
  ['tt_20fastlowess_3a_3aonlineoutput_20tt_22',['&lt;tt&gt;fastlowess::OnlineOutput&lt;/tt&gt;',['../md_docs_2api-online.html#autotoc_md29',1,'']]],
  ['tt_20fastlowess_3a_3astreaminglowess_20tt_23',['&lt;tt&gt;fastlowess::StreamingLowess&lt;/tt&gt;',['../md_docs_2api-streaming.html#autotoc_md35',1,'']]],
  ['tt_20lowessoptions_20tt_24',['&lt;tt&gt;LowessOptions&lt;/tt&gt;',['../md_docs_2api.html#autotoc_md48',1,'']]],
  ['tt_20onlineoptions_20tt_20inherits_20tt_20lowessoptions_20tt_25',['&lt;tt&gt;OnlineOptions&lt;/tt&gt; (inherits &lt;tt&gt;LowessOptions&lt;/tt&gt;)',['../md_docs_2api-online.html#autotoc_md27',1,'']]],
  ['tt_20streamingoptions_20tt_20inherits_20tt_20lowessoptions_20tt_26',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LowessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md39',1,'']]]
];
