var searchData=
[
  ['challenge_0',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md277',1,'']]],
  ['checking_20availability_1',['Checking Availability',['../md_docs_2gpu-backend.html#autotoc_md124',1,'']]],
  ['chip_20seq_20signal_20smoothing_2',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md280',1,'']]],
  ['choosing_20a_20kernel_3',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md171',1,'']]],
  ['choosing_20a_20policy_4',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md66',1,'']]],
  ['choosing_20a_20scaling_20method_5',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md272',1,'']]],
  ['choosing_20a_20strategy_6',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md183',1,'']]],
  ['choosing_20fraction_20for_20time_20series_7',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md321',1,'']]],
  ['choosing_20parameters_8',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md299',1,'']]],
  ['chunk_20processing_9',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md294',1,'']]],
  ['chunk_5fsize_10',['chunk_size',['../md_docs_2parameters.html#autotoc_md225',1,'']]],
  ['class_11',['class',['../md_docs_2api-streaming.html#autotoc_md15',1,'Class'],['../md_docs_2api-online.html#autotoc_md5',1,'Class']]],
  ['classes_12',['Classes',['../md_docs_2api.html#autotoc_md26',1,'']]],
  ['combined_20with_20robustness_20iterations_13',['Combined with Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md114',1,'']]],
  ['comparison_14',['comparison',['../md_docs_2robustness.html#autotoc_md256',1,'Comparison'],['../md_docs_2cross-validation.html#autotoc_md92',1,'Comparison'],['../md_docs_2api.html#autotoc_md34',1,'Feature Comparison'],['../md_docs_2gpu-backend.html#autotoc_md122',1,'Feature Comparison']]],
  ['concepts_15',['Concepts',['../index.html',1,'']]],
  ['concepts_2emd_16',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_17',['From conda-forge',['../md_docs_2installation.html#autotoc_md135',1,'']]],
  ['confidence_20intervals_18',['confidence intervals',['../md_docs_2intervals.html#autotoc_md141',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md239',1,'With Confidence Intervals']]],
  ['confidence_20levels_19',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md147',1,'']]],
  ['confidence_20vs_20prediction_20intervals_20',['Confidence vs Prediction Intervals',['../index.html#autotoc_md76',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_21',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md219',1,'']]],
  ['considerations_22',['considerations',['../md_docs_2use-case-real-time.html#autotoc_md303',1,'Performance Considerations'],['../md_docs_2api.html#autotoc_md36',1,'Performance Considerations']]],
  ['convergence_23',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md262',1,'']]],
  ['core_20parameters_24',['Core Parameters',['../md_docs_2parameters.html#autotoc_md189',1,'']]],
  ['cosine_25',['Cosine',['../md_docs_2kernels.html#autotoc_md165',1,'']]],
  ['course_26',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md319',1,'']]],
  ['coverage_20streaming_27',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md283',1,'']]],
  ['cpu_20benchmarks_28',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md50',1,'']]],
  ['cross_20validation_29',['cross validation',['../md_docs_2cross-validation.html',1,'Cross-Validation'],['../md_docs_2cross-validation.html#autotoc_md86',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_30',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['custom_20weights_31',['custom weights',['../md_docs_2custom-weights.html',1,'Custom Weights'],['../md_docs_2custom-weights.html#autotoc_md104',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_32',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md105',1,'']]],
  ['custom_20weights_20work_33',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md102',1,'']]],
  ['custom_2dweights_2emd_34',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['custom_5fweights_35',['custom_weights',['../md_docs_2parameters.html#autotoc_md208',1,'']]],
  ['cv_20methods_36',['CV Methods',['../md_docs_2parameters.html#autotoc_md221',1,'']]],
  ['cv_20metrics_37',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md94',1,'']]],
  ['cv_5fmethod_38',['cv_method',['../md_docs_2parameters.html#autotoc_md222',1,'']]]
];
