var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md329',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md266',1,'']]],
  ['scaling_2',['scaling',['../md_docs_2scaling.html',1,'']]],
  ['scaling_20method_3',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md278',1,'']]],
  ['scaling_20methods_4',['Scaling Methods',['../md_docs_2scaling.html#autotoc_md269',1,'']]],
  ['scaling_2emd_5',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_6',['scaling_method',['../md_docs_2parameters.html#autotoc_md208',1,'scaling_method'],['../md_docs_2api.html#autotoc_md40',1,'scaling_method']]],
  ['see_20also_7',['see also',['../md_docs_2use-case-time-series.html#autotoc_md335',1,'See Also'],['../md_docs_2gpu-backend.html#autotoc_md129',1,'See also'],['../md_docs_2custom-weights.html#autotoc_md118',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md299',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md317',1,'See Also']]],
  ['seeded_20randomization_8',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md90',1,'']]],
  ['sensor_20data_20example_9',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md304',1,'']]],
  ['seq_20signal_20smoothing_10',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md292',1,'']]],
  ['series_11',['series',['../md_docs_2use-case-time-series.html#autotoc_md333',1,'Choosing Fraction for Time Series'],['../md_docs_2use-case-time-series.html',1,'use-case-time-series']]],
  ['series_20analysis_12',['Time Series Analysis',['../md_docs_2use-case-time-series.html#autotoc_md318',1,'']]],
  ['signal_20smoothing_13',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md292',1,'']]],
  ['smoothing_14',['smoothing',['../md_docs_2quickstart.html#autotoc_md243',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md292',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md285',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md288',1,'Methylation Profile Smoothing']]],
  ['solution_15',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md290',1,'']]],
  ['source_16',['From Source',['../md_docs_2installation.html#autotoc_md134',1,'']]],
  ['standard_20errors_17',['Standard Errors',['../md_docs_2intervals.html#autotoc_md149',1,'']]],
  ['start_18',['Quick Start',['../md_docs_2quickstart.html#autotoc_md242',1,'']]],
  ['steps_19',['steps',['../md_docs_2quickstart.html#autotoc_md251',1,'Next Steps'],['../index.html#autotoc_md82',1,'Next Steps']]],
  ['strategies_20',['strategies',['../md_docs_2merge.html#autotoc_md172',1,'Merge Strategies'],['../md_docs_2streaming.html#autotoc_md282',1,'Merge Strategies']]],
  ['strategy_21',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md183',1,'']]],
  ['streaming_22',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md295',1,'']]],
  ['streaming_20adapter_23',['Streaming Adapter',['../md_docs_2streaming.html',1,'']]],
  ['streaming_20mode_24',['streaming mode',['../md_docs_2quickstart.html#autotoc_md249',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md313',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_25',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md306',1,'']]],
  ['streaming_2emd_26',['streaming.md',['../streaming_8md.html',1,'']]],
  ['streaminglowess_20api_27',['StreamingLowess API',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20tt_20inherits_20tt_20lowessoptions_20tt_28',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LowessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md18',1,'']]],
  ['structure_29',['structure',['../md_docs_2api-streaming.html#autotoc_md17',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md6',1,'Options Structure'],['../md_docs_2api.html#autotoc_md33',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md15',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md8',1,'Result Structure']]],
  ['structures_30',['Options Structures',['../md_docs_2api.html#autotoc_md24',1,'']]],
  ['summary_31',['Parameter Options Summary',['../md_docs_2parameters.html#autotoc_md193',1,'']]],
  ['support_32',['support',['../md_docs_2api.html#autotoc_md27',1,'Enabling GPU Support'],['../md_docs_2gpu-backend.html#autotoc_md126',1,'Installing GPU Support']]],
  ['supported_20features_33',['supported features',['../md_docs_2api.html#autotoc_md29',1,'Supported Features'],['../md_docs_2gpu-backend.html#autotoc_md121',1,'Supported Features']]],
  ['suppress_20a_20known_20outlier_34',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md108',1,'']]]
];
