var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md323',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md260',1,'']]],
  ['scaling_2',['scaling',['../md_docs_2scaling.html',1,'']]],
  ['scaling_20method_3',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md272',1,'']]],
  ['scaling_20methods_4',['Scaling Methods',['../md_docs_2scaling.html#autotoc_md263',1,'']]],
  ['scaling_2emd_5',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_6',['scaling_method',['../md_docs_2parameters.html#autotoc_md202',1,'scaling_method'],['../md_docs_2api.html#autotoc_md40',1,'scaling_method']]],
  ['see_20also_7',['see also',['../md_docs_2use-case-time-series.html#autotoc_md329',1,'See Also'],['../md_docs_2gpu-backend.html#autotoc_md123',1,'See also'],['../md_docs_2custom-weights.html#autotoc_md112',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md293',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md311',1,'See Also']]],
  ['seeded_20randomization_8',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md84',1,'']]],
  ['sensor_20data_20example_9',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md298',1,'']]],
  ['seq_20signal_20smoothing_10',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md286',1,'']]],
  ['series_11',['series',['../md_docs_2use-case-time-series.html#autotoc_md327',1,'Choosing Fraction for Time Series'],['../md_docs_2use-case-time-series.html',1,'use-case-time-series']]],
  ['series_20analysis_12',['Time Series Analysis',['../md_docs_2use-case-time-series.html#autotoc_md312',1,'']]],
  ['signal_20smoothing_13',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md286',1,'']]],
  ['smoothing_14',['smoothing',['../md_docs_2quickstart.html#autotoc_md237',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md286',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md279',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md282',1,'Methylation Profile Smoothing']]],
  ['solution_15',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md284',1,'']]],
  ['source_16',['From Source',['../md_docs_2installation.html#autotoc_md128',1,'']]],
  ['standard_20errors_17',['Standard Errors',['../md_docs_2intervals.html#autotoc_md143',1,'']]],
  ['start_18',['Quick Start',['../md_docs_2quickstart.html#autotoc_md236',1,'']]],
  ['steps_19',['steps',['../md_docs_2quickstart.html#autotoc_md245',1,'Next Steps'],['../index.html#autotoc_md76',1,'Next Steps']]],
  ['strategies_20',['strategies',['../md_docs_2merge.html#autotoc_md166',1,'Merge Strategies'],['../md_docs_2streaming.html#autotoc_md276',1,'Merge Strategies']]],
  ['strategy_21',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md177',1,'']]],
  ['streaming_22',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md289',1,'']]],
  ['streaming_20adapter_23',['Streaming Adapter',['../md_docs_2streaming.html',1,'']]],
  ['streaming_20mode_24',['streaming mode',['../md_docs_2quickstart.html#autotoc_md243',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md307',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_25',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md300',1,'']]],
  ['streaming_2emd_26',['streaming.md',['../streaming_8md.html',1,'']]],
  ['streaminglowess_20—_20c_20api_20reference_27',['StreamingLowess — C++ API Reference',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20tt_20inherits_20tt_20lowessoptions_20tt_28',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LowessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md18',1,'']]],
  ['structure_29',['structure',['../md_docs_2api-streaming.html#autotoc_md17',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md6',1,'Options Structure'],['../md_docs_2api.html#autotoc_md33',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md15',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md8',1,'Result Structure']]],
  ['structures_30',['Options Structures',['../md_docs_2api.html#autotoc_md24',1,'']]],
  ['summary_31',['Parameter Options Summary',['../md_docs_2parameters.html#autotoc_md187',1,'']]],
  ['support_32',['support',['../md_docs_2api.html#autotoc_md27',1,'Enabling GPU Support'],['../md_docs_2gpu-backend.html#autotoc_md120',1,'Installing GPU Support']]],
  ['supported_20features_33',['supported features',['../md_docs_2api.html#autotoc_md29',1,'Supported Features'],['../md_docs_2gpu-backend.html#autotoc_md115',1,'Supported Features']]],
  ['suppress_20a_20known_20outlier_34',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md102',1,'']]]
];
