var searchData=
[
  ['randomization_0',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md111',1,'']]],
  ['readme_2emd_1',['README.md',['../README_8md.html',1,'']]],
  ['real_20time_20dashboard_20example_2',['Real-Time Dashboard Example',['../md_docs_2use-case-real-time.html#autotoc_md318',1,'']]],
  ['real_20time_20processing_3',['Real-Time Processing',['../md_docs_2use-case-real-time.html',1,'']]],
  ['reference_4',['reference',['../index.html#autotoc_md13',1,'API Reference'],['../md_docs_2parameters.html#autotoc_md206',1,'Quick Reference']]],
  ['reflect_5',['Reflect',['../md_docs_2boundary.html#autotoc_md79',1,'']]],
  ['reproducing_20benchmarks_6',['Reproducing Benchmarks',['../md_docs_2benchmarks.html#autotoc_md73',1,'']]],
  ['requirements_7',['Hardware Requirements',['../md_docs_2api.html#autotoc_md54',1,'']]],
  ['residual_8',['residual',['../md_docs_2scaling.html#autotoc_md289',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md291',1,'Mean — Mean Absolute Residual']]],
  ['result_20structure_9',['result structure',['../md_docs_2api-online.html#autotoc_md28',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md36',1,'Result Structure'],['../md_docs_2api.html#autotoc_md56',1,'Result Structure']]],
  ['results_10',['Interpreting Results',['../md_docs_2cross-validation.html#autotoc_md117',1,'']]],
  ['return_5fdiagnostics_11',['return_diagnostics',['../md_docs_2parameters.html#autotoc_md234',1,'']]],
  ['return_5fresiduals_12',['return_residuals',['../md_docs_2parameters.html#autotoc_md232',1,'']]],
  ['return_5frobustness_5fweights_13',['return_robustness_weights',['../md_docs_2parameters.html#autotoc_md236',1,'']]],
  ['return_5fse_14',['return_se',['../md_docs_2parameters.html#autotoc_md238',1,'']]],
  ['robustness_15',['robustness',['../md_docs_2robustness.html',1,'Robustness'],['../index.html#autotoc_md10',1,'Robustness']]],
  ['robustness_20iterations_16',['robustness iterations',['../md_docs_2custom-weights.html#autotoc_md135',1,'Combined with Robustness Iterations'],['../md_docs_2custom-weights.html#autotoc_md126',1,'Custom Weights vs. Robustness Iterations'],['../md_docs_2concepts.html#autotoc_md93',1,'Robustness Iterations']]],
  ['robustness_20methods_17',['Robustness Methods',['../md_docs_2robustness.html#autotoc_md270',1,'']]],
  ['robustness_20works_18',['How Robustness Works',['../md_docs_2robustness.html#autotoc_md268',1,'']]],
  ['robustness_2emd_19',['robustness.md',['../robustness_8md.html',1,'']]],
  ['robustness_5fmethod_20',['robustness_method',['../md_docs_2parameters.html#autotoc_md219',1,'robustness_method'],['../md_docs_2api.html#autotoc_md61',1,'robustness_method']]],
  ['rules_21',['Validation Rules',['../md_docs_2custom-weights.html#autotoc_md137',1,'']]]
];
