var searchData=
[
  ['randomization_0',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md90',1,'']]],
  ['real_20time_1',['use-case-real-time',['../md_docs_2use-case-real-time.html',1,'']]],
  ['real_20time_20dashboard_20example_2',['Real-Time Dashboard Example',['../md_docs_2use-case-real-time.html#autotoc_md309',1,'']]],
  ['real_20time_20processing_3',['Real-Time Processing',['../md_docs_2use-case-real-time.html#autotoc_md300',1,'']]],
  ['reference_4',['Quick Reference',['../md_docs_2parameters.html#autotoc_md191',1,'']]],
  ['reflect_5',['Reflect',['../md_docs_2boundary.html#autotoc_md60',1,'']]],
  ['reproducing_20benchmarks_6',['Reproducing Benchmarks',['../md_docs_2benchmarks.html#autotoc_md54',1,'']]],
  ['requirements_7',['Hardware Requirements',['../md_docs_2api.html#autotoc_md31',1,'']]],
  ['residual_8',['residual',['../md_docs_2scaling.html#autotoc_md274',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md276',1,'Mean — Mean Absolute Residual']]],
  ['result_20structure_9',['result structure',['../md_docs_2api.html#autotoc_md33',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md15',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md8',1,'Result Structure']]],
  ['results_10',['Interpreting Results',['../md_docs_2cross-validation.html#autotoc_md96',1,'']]],
  ['return_5fdiagnostics_11',['return_diagnostics',['../md_docs_2parameters.html#autotoc_md219',1,'']]],
  ['return_5fresiduals_12',['return_residuals',['../md_docs_2parameters.html#autotoc_md217',1,'']]],
  ['return_5frobustness_5fweights_13',['return_robustness_weights',['../md_docs_2parameters.html#autotoc_md221',1,'']]],
  ['return_5fse_14',['return_se',['../md_docs_2parameters.html#autotoc_md223',1,'']]],
  ['robustness_15',['robustness',['../md_docs_2robustness.html',1,'robustness'],['../md_docs_2robustness.html#autotoc_md252',1,'Robustness']]],
  ['robustness_20iterations_16',['robustness iterations',['../md_docs_2custom-weights.html#autotoc_md114',1,'Combined with Robustness Iterations'],['../md_docs_2custom-weights.html#autotoc_md105',1,'Custom Weights vs. Robustness Iterations'],['../index.html#autotoc_md74',1,'Robustness Iterations']]],
  ['robustness_20methods_17',['Robustness Methods',['../md_docs_2robustness.html#autotoc_md255',1,'']]],
  ['robustness_20works_18',['How Robustness Works',['../md_docs_2robustness.html#autotoc_md253',1,'']]],
  ['robustness_2emd_19',['robustness.md',['../robustness_8md.html',1,'']]],
  ['robustness_5fmethod_20',['robustness_method',['../md_docs_2parameters.html#autotoc_md204',1,'robustness_method'],['../md_docs_2api.html#autotoc_md38',1,'robustness_method']]],
  ['rules_21',['Validation Rules',['../md_docs_2custom-weights.html#autotoc_md116',1,'']]]
];
