var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md319',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md262',1,'']]],
  ['scaling_20method_2',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md274',1,'']]],
  ['scaling_20methods_3',['Scaling Methods',['../md_docs_2scaling.html',1,'']]],
  ['scaling_2emd_4',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_5',['scaling_method',['../md_docs_2parameters.html#autotoc_md204',1,'scaling_method'],['../md_docs_2api.html#autotoc_md44',1,'scaling_method']]],
  ['see_20also_6',['see also',['../md_docs_2use-case-time-series.html#autotoc_md325',1,'See Also'],['../md_docs_2gpu-backend.html#autotoc_md131',1,'See also'],['../md_docs_2custom-weights.html#autotoc_md120',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md289',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md307',1,'See Also']]],
  ['seeded_20randomization_7',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md92',1,'']]],
  ['sensor_20data_20example_8',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md294',1,'']]],
  ['seq_20signal_20smoothing_9',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md282',1,'']]],
  ['series_10',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md323',1,'']]],
  ['series_20analysis_11',['Time Series Analysis',['../md_docs_2use-case-time-series.html',1,'']]],
  ['signal_20smoothing_12',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md282',1,'']]],
  ['smoothing_13',['smoothing',['../md_docs_2quickstart.html#autotoc_md239',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md282',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md278',1,'Methylation Profile Smoothing']]],
  ['solution_14',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md280',1,'']]],
  ['source_15',['From Source',['../md_docs_2installation.html#autotoc_md136',1,'']]],
  ['standard_20errors_16',['Standard Errors',['../md_docs_2intervals.html#autotoc_md151',1,'']]],
  ['start_17',['Quick Start',['../md_docs_2quickstart.html',1,'']]],
  ['steps_18',['steps',['../md_docs_2quickstart.html#autotoc_md247',1,'Next Steps'],['../index.html#autotoc_md84',1,'Next Steps']]],
  ['strategies_19',['Merge Strategies',['../md_docs_2merge.html',1,'']]],
  ['strategy_20',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md185',1,'']]],
  ['streaming_21',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md285',1,'']]],
  ['streaming_20mode_22',['streaming mode',['../md_docs_2use-case-real-time.html#autotoc_md303',1,'Streaming Mode'],['../md_docs_2quickstart.html#autotoc_md245',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_23',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md296',1,'']]],
  ['streaminglowess_20api_24',['StreamingLowess API',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20tt_20inherits_20tt_20lowessoptions_20tt_25',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LowessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md20',1,'']]],
  ['structure_26',['structure',['../md_docs_2api-streaming.html#autotoc_md19',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md7',1,'Options Structure'],['../md_docs_2api-streaming.html#autotoc_md17',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md9',1,'Result Structure'],['../md_docs_2api.html#autotoc_md37',1,'Result Structure']]],
  ['structures_27',['Options Structures',['../md_docs_2api.html#autotoc_md28',1,'']]],
  ['summary_28',['Parameter Options Summary',['../md_docs_2parameters.html#autotoc_md189',1,'']]],
  ['support_29',['support',['../md_docs_2api.html#autotoc_md31',1,'Enabling GPU Support'],['../md_docs_2gpu-backend.html#autotoc_md128',1,'Installing GPU Support']]],
  ['supported_20features_30',['supported features',['../md_docs_2api.html#autotoc_md33',1,'Supported Features'],['../md_docs_2gpu-backend.html#autotoc_md123',1,'Supported Features']]],
  ['suppress_20a_20known_20outlier_31',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md110',1,'']]]
];
