var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md304',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md247',1,'']]],
  ['scaling_20method_2',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md259',1,'']]],
  ['scaling_20methods_3',['Scaling Methods',['../md_docs_2scaling.html',1,'']]],
  ['scaling_2emd_4',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_5',['scaling_method',['../md_docs_2api.html#autotoc_md53',1,'']]],
  ['see_20also_6',['see also',['../md_docs_2use-case-time-series.html#autotoc_md310',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md123',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md274',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md292',1,'See Also']]],
  ['seeded_20randomization_7',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md98',1,'']]],
  ['sensor_20data_20example_8',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md279',1,'']]],
  ['seq_20signal_20smoothing_9',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md267',1,'']]],
  ['series_10',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md308',1,'']]],
  ['series_20analysis_11',['Time Series Analysis',['../md_docs_2use-case-time-series.html',1,'']]],
  ['signal_20smoothing_12',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md267',1,'']]],
  ['smoothing_13',['smoothing',['../md_docs_2quickstart.html#autotoc_md224',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md267',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md263',1,'Methylation Profile Smoothing']]],
  ['solution_14',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md265',1,'']]],
  ['source_15',['From Source',['../md_docs_2installation.html#autotoc_md140',1,'']]],
  ['speed_16',['Speed',['../index.html#autotoc_md7',1,'']]],
  ['standard_20errors_17',['Standard Errors',['../md_docs_2intervals.html#autotoc_md155',1,'']]],
  ['start_18',['Quick Start',['../md_docs_2quickstart.html',1,'']]],
  ['steps_19',['steps',['../md_docs_2quickstart.html#autotoc_md232',1,'Next Steps'],['../md_docs_2concepts.html#autotoc_md90',1,'Next Steps']]],
  ['strategies_20',['Merge Strategies',['../md_docs_2merge.html',1,'']]],
  ['strategy_21',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md189',1,'']]],
  ['streaming_22',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md270',1,'']]],
  ['streaming_20mode_23',['streaming mode',['../md_docs_2quickstart.html#autotoc_md230',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md288',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_24',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md281',1,'']]],
  ['streaminglowess_20api_25',['StreamingLowess API',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20inherits_20lowessoptions_26',['StreamingOptions (inherits LowessOptions)',['../md_docs_2api-streaming.html#autotoc_md35',1,'']]],
  ['structure_27',['structure',['../md_docs_2api-streaming.html#autotoc_md34',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md22',1,'Options Structure'],['../md_docs_2api-streaming.html#autotoc_md32',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md24',1,'Result Structure'],['../md_docs_2api.html#autotoc_md46',1,'Result Structure']]],
  ['structures_28',['Options Structures',['../md_docs_2api.html#autotoc_md43',1,'']]],
  ['support_29',['Installing GPU Support',['../md_docs_2gpu-backend.html#autotoc_md131',1,'']]],
  ['supported_20features_30',['Supported Features',['../md_docs_2gpu-backend.html#autotoc_md126',1,'']]],
  ['suppress_20a_20known_20outlier_31',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md114',1,'']]]
];
