var searchData=
[
  ['backend_0',['backend',['../md_docs_2gpu-backend.html#autotoc_md119',1,'GPU Backend'],['../md_docs_2benchmarks.html#autotoc_md52',1,'GPU Backend'],['../md_docs_2gpu-backend.html',1,'gpu-backend']]],
  ['basic_20smoothing_1',['Basic Smoothing',['../md_docs_2quickstart.html#autotoc_md243',1,'']]],
  ['basic_20trend_20extraction_2',['Basic Trend Extraction',['../md_docs_2use-case-time-series.html#autotoc_md321',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../md_docs_2custom-weights.html#autotoc_md107',1,'']]],
  ['batch_20adapter_4',['Batch Adapter',['../md_docs_2batch.html',1,'']]],
  ['batch_2emd_5',['batch.md',['../batch_8md.html',1,'']]],
  ['benchmarks_6',['benchmarks',['../md_docs_2benchmarks.html#autotoc_md49',1,'Benchmarks'],['../md_docs_2benchmarks.html',1,'benchmarks'],['../md_docs_2benchmarks.html#autotoc_md50',1,'CPU Benchmarks'],['../md_docs_2benchmarks.html#autotoc_md54',1,'Reproducing Benchmarks']]],
  ['benchmarks_2emd_7',['benchmarks.md',['../benchmarks_8md.html',1,'']]],
  ['best_20practices_8',['Best Practices',['../md_docs_2cross-validation.html#autotoc_md100',1,'']]],
  ['best_20practices_20for_20genomic_20data_9',['Best Practices for Genomic Data',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['binaries_20linux_20x64_10',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md131',1,'']]],
  ['binaries_20macos_20x64_11',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md132',1,'']]],
  ['binaries_20windows_20x64_12',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md133',1,'']]],
  ['bisquare_20default_13',['Bisquare (Default)',['../md_docs_2robustness.html#autotoc_md256',1,'']]],
  ['biweight_14',['Biweight',['../md_docs_2kernels.html#autotoc_md163',1,'']]],
  ['both_20intervals_15',['Both Intervals',['../md_docs_2intervals.html#autotoc_md145',1,'']]],
  ['boundary_16',['boundary',['../md_docs_2boundary.html',1,'boundary'],['../md_docs_2boundary.html#autotoc_md64',1,'No Boundary']]],
  ['boundary_20handling_17',['Boundary Handling',['../md_docs_2boundary.html#autotoc_md55',1,'']]],
  ['boundary_2emd_18',['boundary.md',['../boundary_8md.html',1,'']]],
  ['boundary_5fpolicy_19',['boundary_policy',['../md_docs_2parameters.html#autotoc_md206',1,'boundary_policy'],['../md_docs_2api.html#autotoc_md39',1,'boundary_policy']]],
  ['built_20binaries_20linux_20x64_20',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md131',1,'']]],
  ['built_20binaries_20macos_20x64_21',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md132',1,'']]],
  ['built_20binaries_20windows_20x64_22',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md133',1,'']]],
  ['by_20point_23',['Online Mode: Point-by-Point',['../md_docs_2use-case-real-time.html#autotoc_md303',1,'']]]
];
