var searchData=
[
  ['fastlowess_0',['fastLowess',['../index.html',1,'']]],
  ['fastlowess_3a_3adiagnostics_20tt_1',['&lt;tt&gt;fastlowess::Diagnostics&lt;/tt&gt;',['../md_docs_2api.html#autotoc_md58',1,'']]],
  ['fastlowess_3a_3alowess_20tt_2',['&lt;tt&gt;fastlowess::Lowess&lt;/tt&gt;',['../md_docs_2api.html#autotoc_md46',1,'']]],
  ['fastlowess_3a_3alowessresult_20tt_3',['fastlowess::lowessresult tt',['../md_docs_2api-streaming.html#autotoc_md37',1,'&lt;tt&gt;fastlowess::LowessResult&lt;/tt&gt;'],['../md_docs_2api.html#autotoc_md57',1,'&lt;tt&gt;fastlowess::LowessResult&lt;/tt&gt;']]],
  ['fastlowess_3a_3aonlinelowess_20tt_4',['&lt;tt&gt;fastlowess::OnlineLowess&lt;/tt&gt;',['../md_docs_2api-online.html#autotoc_md25',1,'']]],
  ['fastlowess_3a_3aonlineoutput_20tt_5',['&lt;tt&gt;fastlowess::OnlineOutput&lt;/tt&gt;',['../md_docs_2api-online.html#autotoc_md29',1,'']]],
  ['fastlowess_3a_3astreaminglowess_20tt_6',['&lt;tt&gt;fastlowess::StreamingLowess&lt;/tt&gt;',['../md_docs_2api-streaming.html#autotoc_md35',1,'']]],
  ['feature_20comparison_7',['feature comparison',['../md_docs_2gpu-backend.html#autotoc_md143',1,'Feature Comparison'],['../md_docs_2api.html#autotoc_md53',1,'Feature Comparison']]],
  ['features_8',['features',['../index.html#autotoc_md11',1,'Features'],['../md_docs_2api.html#autotoc_md52',1,'Supported Features'],['../md_docs_2gpu-backend.html#autotoc_md142',1,'Supported Features']]],
  ['file_20processing_9',['Log File Processing',['../md_docs_2use-case-real-time.html#autotoc_md316',1,'']]],
  ['first_10',['Take First',['../md_docs_2merge.html#autotoc_md198',1,'']]],
  ['fold_20cross_20validation_11',['K-Fold Cross-Validation',['../md_docs_2cross-validation.html#autotoc_md107',1,'']]],
  ['for_20genomic_20data_12',['Best Practices for Genomic Data',['../md_docs_2use-case-genomics.html#autotoc_md306',1,'']]],
  ['for_20time_20series_13',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'']]],
  ['forecasting_20with_20prediction_20intervals_14',['Forecasting with Prediction Intervals',['../md_docs_2use-case-time-series.html#autotoc_md334',1,'']]],
  ['forge_15',['From conda-forge',['../md_docs_2installation.html#autotoc_md156',1,'']]],
  ['fraction_16',['fraction',['../md_docs_2parameters.html#autotoc_md211',1,'']]],
  ['fraction_20for_20time_20series_17',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'']]],
  ['fraction_20parameter_18',['The Fraction Parameter',['../md_docs_2concepts.html#autotoc_md91',1,'']]],
  ['from_20conda_20forge_19',['From conda-forge',['../md_docs_2installation.html#autotoc_md156',1,'']]],
  ['from_20source_20',['From Source',['../md_docs_2installation.html#autotoc_md155',1,'']]],
  ['full_20documentation_20a_21',['📚 &lt;a href=&quot;https://thisisamirv.github.io/lowess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['functions_22',['Weight Functions',['../md_docs_2kernels.html',1,'']]]
];
