var searchData=
[
  ['a_20href_20https_3a_20thisisamirv_20github_20io_20lowess_20project_20cpp_20view_20the_20full_20documentation_20a_0',['📚 &lt;a href=&quot;https://thisisamirv.github.io/lowess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['a_20kernel_1',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md192',1,'']]],
  ['a_20known_20outlier_2',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md129',1,'']]],
  ['a_20policy_3',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md85',1,'']]],
  ['a_20scaling_20method_4',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md293',1,'']]],
  ['a_20strategy_5',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md204',1,'']]],
  ['absolute_20deviation_20default_6',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md287',1,'']]],
  ['absolute_20residual_7',['absolute residual',['../md_docs_2scaling.html#autotoc_md289',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md291',1,'Mean — Mean Absolute Residual']]],
  ['acceleration_8',['GPU Acceleration',['../md_docs_2api.html#autotoc_md49',1,'']]],
  ['adapter_20parameters_9',['Adapter Parameters',['../md_docs_2parameters.html#autotoc_md245',1,'']]],
  ['adapter_2dchoice_2emd_10',['adapter-choice.md',['../adapter-choice_8md.html',1,'']]],
  ['advantages_11',['Key Advantages',['../md_docs_2concepts.html#autotoc_md101',1,'']]],
  ['also_12',['also',['../md_docs_2use-case-real-time.html#autotoc_md326',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md139',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md308',1,'See Also'],['../md_docs_2gpu-backend.html#autotoc_md150',1,'See also'],['../md_docs_2use-case-time-series.html#autotoc_md344',1,'See Also']]],
  ['analysis_13',['analysis',['../md_docs_2use-case-time-series.html#autotoc_md338',1,'Multi-Scale Analysis'],['../md_docs_2use-case-time-series.html',1,'Time Series Analysis']]],
  ['api_14',['api',['../md_docs_2api.html',1,'API'],['../md_docs_2api-online.html',1,'OnlineLowess API'],['../md_docs_2api-streaming.html',1,'StreamingLowess API']]],
  ['api_20reference_15',['API Reference',['../index.html#autotoc_md13',1,'']]],
  ['api_2donline_2emd_16',['api-online.md',['../api-online_8md.html',1,'']]],
  ['api_2dstreaming_2emd_17',['api-streaming.md',['../api-streaming_8md.html',1,'']]],
  ['api_2emd_18',['api.md',['../api_8md.html',1,'']]],
  ['application_19',['Application',['../md_docs_2use-case-genomics.html#autotoc_md302',1,'']]],
  ['auto_20convergence_20',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md283',1,'']]],
  ['auto_5fconverge_21',['auto_converge',['../md_docs_2parameters.html#autotoc_md227',1,'']]],
  ['availability_22',['availability',['../md_docs_2intervals.html#autotoc_md172',1,'Availability'],['../md_docs_2cross-validation.html#autotoc_md119',1,'Availability'],['../md_docs_2gpu-backend.html#autotoc_md145',1,'Checking Availability']]],
  ['available_20kernels_23',['Available Kernels',['../md_docs_2kernels.html#autotoc_md176',1,'']]],
  ['average_24',['average',['../md_docs_2merge.html#autotoc_md196',1,'Average'],['../md_docs_2merge.html#autotoc_md202',1,'Weighted Average']]]
];
