var searchData=
[
  ['c_20api_20reference_0',['c api reference',['../md_docs_2api.html',1,'fastLowess C++ API Reference'],['../md_docs_2api-online.html',1,'OnlineLowess — C++ API Reference'],['../md_docs_2api-streaming.html',1,'StreamingLowess — C++ API Reference']]],
  ['case_20genomics_1',['use-case-genomics',['../md_docs_2use-case-genomics.html',1,'']]],
  ['case_20real_20time_2',['use-case-real-time',['../md_docs_2use-case-real-time.html',1,'']]],
  ['case_20time_20series_3',['use-case-time-series',['../md_docs_2use-case-time-series.html',1,'']]],
  ['challenge_4',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md289',1,'']]],
  ['checking_20availability_5',['Checking Availability',['../md_docs_2gpu-backend.html#autotoc_md124',1,'']]],
  ['chip_20seq_20signal_20smoothing_6',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md292',1,'']]],
  ['choice_7',['adapter-choice',['../md_docs_2adapter-choice.html',1,'']]],
  ['choosing_20a_20kernel_8',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md171',1,'']]],
  ['choosing_20a_20policy_9',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md66',1,'']]],
  ['choosing_20a_20scaling_20method_10',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md278',1,'']]],
  ['choosing_20a_20strategy_11',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md183',1,'']]],
  ['choosing_20fraction_20for_20time_20series_12',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md333',1,'']]],
  ['choosing_20parameters_13',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['chunk_20processing_14',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md306',1,'']]],
  ['chunk_5fsize_15',['chunk_size',['../md_docs_2parameters.html#autotoc_md231',1,'']]],
  ['class_16',['class',['../md_docs_2api-online.html#autotoc_md4',1,'Class'],['../md_docs_2api-streaming.html#autotoc_md13',1,'Class']]],
  ['classes_17',['Classes',['../md_docs_2api.html#autotoc_md22',1,'']]],
  ['combined_20with_20robustness_20iterations_18',['Combined with Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md114',1,'']]],
  ['comparison_19',['comparison',['../md_docs_2cross-validation.html#autotoc_md92',1,'Comparison'],['../md_docs_2robustness.html#autotoc_md262',1,'Comparison'],['../md_docs_2gpu-backend.html#autotoc_md122',1,'Feature Comparison'],['../md_docs_2api.html#autotoc_md30',1,'Feature Comparison']]],
  ['concepts_20',['Concepts',['../index.html#autotoc_md67',1,'']]],
  ['concepts_2emd_21',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_22',['From conda-forge',['../md_docs_2installation.html#autotoc_md135',1,'']]],
  ['confidence_20intervals_23',['confidence intervals',['../md_docs_2intervals.html#autotoc_md141',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md245',1,'With Confidence Intervals']]],
  ['confidence_20levels_24',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md147',1,'']]],
  ['confidence_20vs_20prediction_20intervals_25',['Confidence vs Prediction Intervals',['../index.html#autotoc_md76',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_26',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md225',1,'']]],
  ['considerations_27',['considerations',['../md_docs_2use-case-real-time.html#autotoc_md315',1,'Performance Considerations'],['../md_docs_2api.html#autotoc_md32',1,'Performance Considerations']]],
  ['convergence_28',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md268',1,'']]],
  ['core_20parameters_29',['Core Parameters',['../md_docs_2parameters.html#autotoc_md195',1,'']]],
  ['cosine_30',['Cosine',['../md_docs_2kernels.html#autotoc_md165',1,'']]],
  ['course_31',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md331',1,'']]],
  ['coverage_20streaming_32',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md295',1,'']]],
  ['cpu_20benchmarks_33',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md50',1,'']]],
  ['cross_20validation_34',['cross validation',['../md_docs_2cross-validation.html#autotoc_md83',1,'Cross-Validation'],['../md_docs_2cross-validation.html',1,'cross-validation'],['../md_docs_2cross-validation.html#autotoc_md86',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_35',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['custom_20weights_36',['custom weights',['../md_docs_2custom-weights.html#autotoc_md101',1,'Custom Weights'],['../md_docs_2custom-weights.html',1,'custom-weights'],['../md_docs_2custom-weights.html#autotoc_md104',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_37',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md105',1,'']]],
  ['custom_20weights_20work_38',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md102',1,'']]],
  ['custom_2dweights_2emd_39',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['custom_5fweights_40',['custom_weights',['../md_docs_2parameters.html#autotoc_md214',1,'']]],
  ['cv_20methods_41',['CV Methods',['../md_docs_2parameters.html#autotoc_md227',1,'']]],
  ['cv_20metrics_42',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md94',1,'']]],
  ['cv_5fmethod_43',['cv_method',['../md_docs_2parameters.html#autotoc_md228',1,'']]]
];
