var searchData=
[
  ['challenge_0',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md298',1,'']]],
  ['changelog_1',['Changelog',['../index.html#autotoc_md16',1,'']]],
  ['checking_20availability_2',['Checking Availability',['../md_docs_2gpu-backend.html#autotoc_md145',1,'']]],
  ['chip_20seq_20signal_20smoothing_3',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md301',1,'']]],
  ['choosing_20a_20kernel_4',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md192',1,'']]],
  ['choosing_20a_20policy_5',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md85',1,'']]],
  ['choosing_20a_20scaling_20method_6',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md293',1,'']]],
  ['choosing_20a_20strategy_7',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md204',1,'']]],
  ['choosing_20fraction_20for_20time_20series_8',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'']]],
  ['choosing_20parameters_9',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md320',1,'']]],
  ['chunk_20processing_10',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md315',1,'']]],
  ['chunk_5fsize_11',['chunk_size',['../md_docs_2parameters.html#autotoc_md246',1,'']]],
  ['citation_12',['Citation',['../index.html#autotoc_md18',1,'']]],
  ['class_13',['class',['../md_docs_2api-online.html#autotoc_md24',1,'Class'],['../md_docs_2api-streaming.html#autotoc_md34',1,'Class']]],
  ['classes_14',['Classes',['../md_docs_2api.html#autotoc_md45',1,'']]],
  ['combined_20with_20robustness_20iterations_15',['Combined with Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md135',1,'']]],
  ['comparison_16',['comparison',['../md_docs_2robustness.html#autotoc_md277',1,'Comparison'],['../md_docs_2cross-validation.html#autotoc_md113',1,'Comparison'],['../md_docs_2gpu-backend.html#autotoc_md143',1,'Feature Comparison'],['../md_docs_2api.html#autotoc_md53',1,'Feature Comparison']]],
  ['concepts_17',['Concepts',['../md_docs_2concepts.html',1,'']]],
  ['concepts_2emd_18',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_19',['From conda-forge',['../md_docs_2installation.html#autotoc_md156',1,'']]],
  ['confidence_20intervals_20',['confidence intervals',['../md_docs_2intervals.html#autotoc_md162',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md260',1,'With Confidence Intervals']]],
  ['confidence_20levels_21',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md168',1,'']]],
  ['confidence_20vs_20prediction_20intervals_22',['Confidence vs Prediction Intervals',['../md_docs_2concepts.html#autotoc_md95',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_23',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md240',1,'']]],
  ['considerations_24',['considerations',['../md_docs_2use-case-real-time.html#autotoc_md324',1,'Performance Considerations'],['../md_docs_2api.html#autotoc_md55',1,'Performance Considerations']]],
  ['contributing_25',['Contributing',['../index.html#autotoc_md15',1,'']]],
  ['convergence_26',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md283',1,'']]],
  ['core_20parameters_27',['Core Parameters',['../md_docs_2parameters.html#autotoc_md210',1,'']]],
  ['cosine_28',['Cosine',['../md_docs_2kernels.html#autotoc_md186',1,'']]],
  ['course_29',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md340',1,'']]],
  ['coverage_20streaming_30',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md304',1,'']]],
  ['cpp_20view_20the_20full_20documentation_20a_31',['📚 &lt;a href=&quot;https://thisisamirv.github.io/lowess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['cpu_20benchmarks_32',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md69',1,'']]],
  ['cross_20validation_33',['cross validation',['../md_docs_2cross-validation.html',1,'Cross-Validation'],['../md_docs_2cross-validation.html#autotoc_md107',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_34',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['custom_20weights_35',['custom weights',['../md_docs_2custom-weights.html',1,'Custom Weights'],['../md_docs_2custom-weights.html#autotoc_md125',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_36',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md126',1,'']]],
  ['custom_20weights_20work_37',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md123',1,'']]],
  ['custom_2dweights_2emd_38',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['custom_5fweights_39',['custom_weights',['../md_docs_2parameters.html#autotoc_md229',1,'']]],
  ['cv_20methods_40',['CV Methods',['../md_docs_2parameters.html#autotoc_md242',1,'']]],
  ['cv_20metrics_41',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md115',1,'']]],
  ['cv_5fmethod_42',['cv_method',['../md_docs_2parameters.html#autotoc_md243',1,'']]]
];
