no_includes = true
header = "#include <stdint.h>\n#include <stddef.h>"
include_guard = "FASTLOWESS_H"
usize_is_size_t = true

[parse]
parse_deps = false

[export]
include = ["CppLowessResult"]
prefix = "fastlowess_"
renaming_overrides_prefixing = true

[fn]
rename_args = "None"

[struct]
rename_fields = "None"

[enum]
rename_variants = "ScreamingSnakeCase"
