#ifndef FASTLOWESS_VERSION_H
#define FASTLOWESS_VERSION_H

#define FASTLOWESS_CPP_VERSION_MAJOR 5
#define FASTLOWESS_CPP_VERSION_MINOR 0
#define FASTLOWESS_CPP_VERSION_PATCH 0
#define FASTLOWESS_CPP_VERSION_STRING "5.0.0"

#endif