#ifndef FASTLOWESS_VERSION_H
#define FASTLOWESS_VERSION_H

#define FASTLOWESS_CPP_VERSION_MAJOR 4
#define FASTLOWESS_CPP_VERSION_MINOR 1
#define FASTLOWESS_CPP_VERSION_PATCH 0
#define FASTLOWESS_CPP_VERSION_STRING "4.1.0"

#endif