
import __ASTRO_IMAGE_IMPORT_0 from "../assets/diagrams/adapter_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fadapter-choice.md";
import __ASTRO_IMAGE_IMPORT_1 from "../assets/diagrams/boundary_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fboundary.md";
import __ASTRO_IMAGE_IMPORT_2 from "../assets/diagrams/boundary_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md";
import __ASTRO_IMAGE_IMPORT_3 from "../assets/diagrams/cv_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcross-validation.md";
import __ASTRO_IMAGE_IMPORT_4 from "../assets/diagrams/gap_handling.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fbatch.md";
import __ASTRO_IMAGE_IMPORT_5 from "../assets/diagrams/intervals_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fintervals.md";
import __ASTRO_IMAGE_IMPORT_6 from "../assets/diagrams/kernel_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fkernels.md";
import __ASTRO_IMAGE_IMPORT_7 from "../assets/diagrams/merge_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmerge.md";
import __ASTRO_IMAGE_IMPORT_8 from "../assets/diagrams/merge_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fstreaming.md";
import __ASTRO_IMAGE_IMPORT_9 from "../assets/diagrams/online_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fonline.md";
import __ASTRO_IMAGE_IMPORT_10 from "../assets/diagrams/robust_iter_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md";
import __ASTRO_IMAGE_IMPORT_11 from "../assets/diagrams/robust_method_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md";
import __ASTRO_IMAGE_IMPORT_12 from "../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md";
import __ASTRO_IMAGE_IMPORT_13 from "../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md";
import __ASTRO_IMAGE_IMPORT_14 from "../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fscaling.md";
import __ASTRO_IMAGE_IMPORT_15 from "../assets/diagrams/zero_weight_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md";
export default new Map([["../assets/diagrams/adapter_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fadapter-choice.md", __ASTRO_IMAGE_IMPORT_0], ["../assets/diagrams/boundary_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fboundary.md", __ASTRO_IMAGE_IMPORT_1], ["../assets/diagrams/boundary_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md", __ASTRO_IMAGE_IMPORT_2], ["../assets/diagrams/cv_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fcross-validation.md", __ASTRO_IMAGE_IMPORT_3], ["../assets/diagrams/gap_handling.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fbatch.md", __ASTRO_IMAGE_IMPORT_4], ["../assets/diagrams/intervals_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fintervals.md", __ASTRO_IMAGE_IMPORT_5], ["../assets/diagrams/kernel_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fkernels.md", __ASTRO_IMAGE_IMPORT_6], ["../assets/diagrams/merge_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fmerge.md", __ASTRO_IMAGE_IMPORT_7], ["../assets/diagrams/merge_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fstreaming.md", __ASTRO_IMAGE_IMPORT_8], ["../assets/diagrams/online_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fonline.md", __ASTRO_IMAGE_IMPORT_9], ["../assets/diagrams/robust_iter_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md", __ASTRO_IMAGE_IMPORT_10], ["../assets/diagrams/robust_method_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md", __ASTRO_IMAGE_IMPORT_11], ["../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md", __ASTRO_IMAGE_IMPORT_12], ["../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Frobustness.md", __ASTRO_IMAGE_IMPORT_13], ["../assets/diagrams/scaling_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fscaling.md", __ASTRO_IMAGE_IMPORT_14], ["../assets/diagrams/zero_weight_comparison.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fparameters.md", __ASTRO_IMAGE_IMPORT_15]]);
		