# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rfastlowess_wrappers", use_symbols = TRUE, package_name = "rfastlowess")

#' @usage NULL
#' @useDynLib rfastlowess, .registration = TRUE
NULL

RLowess <- new.env(parent = emptyenv())

RLowess$new <- function(fraction, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, confidence_intervals, prediction_intervals, return_diagnostics, return_residuals, return_robustness_weights, zero_weight_fallback, auto_converge, cv_fractions, cv_method, cv_k, parallel) .Call(wrap__RLowess__new, fraction, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, confidence_intervals, prediction_intervals, return_diagnostics, return_residuals, return_robustness_weights, zero_weight_fallback, auto_converge, cv_fractions, cv_method, cv_k, parallel)

RLowess$fit <- function(x, y) .Call(wrap__RLowess__fit, self, x, y)

#' @export
`$.RLowess` <- function(self, name) {
    func <- RLowess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RLowess` <- `$.RLowess`

RStreamingLowess <- new.env(parent = emptyenv())

RStreamingLowess$new <- function(fraction, chunk_size, overlap, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, auto_converge, return_diagnostics, return_robustness_weights, parallel) .Call(wrap__RStreamingLowess__new, fraction, chunk_size, overlap, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, auto_converge, return_diagnostics, return_robustness_weights, parallel)

RStreamingLowess$process_chunk <- function(x, y) .Call(wrap__RStreamingLowess__process_chunk, self, x, y)

RStreamingLowess$finalize <- function() .Call(wrap__RStreamingLowess__finalize, self)

#' @export
`$.RStreamingLowess` <- function(self, name) {
    func <- RStreamingLowess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RStreamingLowess` <- `$.RStreamingLowess`

ROnlineLowess <- new.env(parent = emptyenv())

ROnlineLowess$new <- function(fraction, window_capacity, min_points, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, update_mode, auto_converge, return_robustness_weights, parallel) .Call(wrap__ROnlineLowess__new, fraction, window_capacity, min_points, iterations, delta, weight_function, robustness_method, scaling_method, boundary_policy, update_mode, auto_converge, return_robustness_weights, parallel)

ROnlineLowess$add_points <- function(x, y) .Call(wrap__ROnlineLowess__add_points, self, x, y)

#' @export
`$.ROnlineLowess` <- function(self, name) {
    func <- ROnlineLowess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.ROnlineLowess` <- `$.ROnlineLowess`


# nolint end
